//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HearMyName
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppEvent
    {
        public int ID { get; set; }
        public int RecordingID { get; set; }
        public string ActionPerformed { get; set; }
        public string NewStatus { get; set; }
        public int PerformedBy { get; set; }
        public System.DateTime PerformedOn { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual StudentRecording StudentRecording { get; set; }
    }
}
