//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HearMyName
{
    using System;
    using System.Collections.Generic;
    
    public partial class LatestRecordingStatus
    {
        public int StudentCWID { get; set; }
        public string StudentName { get; set; }
        public string StudentPreferredName { get; set; }
        public string StudentEmail { get; set; }
        public string Pronounciation { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ActionPerformed { get; set; }
        public Nullable<System.DateTime> PerformedOn { get; set; }
        public string NewStatus { get; set; }
        public Nullable<bool> isReviewed { get; set; }
        public int ID { get; set; }
    }
}
