//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HearMyName
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserList
    {
        public Nullable<int> userCWID { get; set; }
        public string UserName { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
    }
}
